### ISSUE TITLE
JWT::DecodeError (Nil JSON web token)

### ISSUE THREAD

**Issue by serhiijun** [tiltcamp/omniauth-outseta#7]
```
Started GET "/auth/outseta/callback?confirmationToken=dbc7a36328333e8d439019f3d14128bf" for 92.249.90.56 at 2024-02-14 01:19:19 +0200
Cannot render console from 92.249.90.56! Allowed networks: 127.0.0.0/127.255.255.255, ::1
I, [2024-02-14T01:19:19.806721 #59888]  INFO -- omniauth: (outseta) Callback phase initiated.

JWT::DecodeError (Nil JSON web token):

jwt (2.7.1) lib/jwt/decode.rb:13:in `initialize'
jwt (2.7.1) lib/jwt.rb:29:in `new'
jwt (2.7.1) lib/jwt.rb:29:in `decode'
omniauth-outseta (1.0.2) lib/omniauth/strategies/outseta.rb:59:in `raw_info'
omniauth-outseta (1.0.2) lib/omniauth/strategies/outseta.rb:18:in `block in <class:Outseta>'
omniauth (1.9.2) lib/omniauth/strategy.rb:109:in `instance_eval'
omniauth (1.9.2) lib/omniauth/strategy.rb:109:in `block in compile_stack'
omniauth (1.9.2) lib/omniauth/strategy.rb:108:in `each'
omniauth (1.9.2) lib/omniauth/strategy.rb:108:in `inject'
omniauth (1.9.2) lib/omniauth/strategy.rb:108:in `compile_stack'
omniauth (1.9.2) lib/omniauth/strategy.rb:102:in `uid_stack'
omniauth (1.9.2) lib/omniauth/strategy.rb:332:in `uid'
omniauth (1.9.2) lib/omniauth/strategy.rb:348:in `auth_hash'
omniauth (1.9.2) lib/omniauth/strategy.rb:372:in `callback_phase'
omniauth (1.9.2) lib/omniauth/strategy.rb:238:in `callback_call'
omniauth (1.9.2) lib/omniauth/strategy.rb:189:in `call!'
omniauth (1.9.2) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.2) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.2) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.2) lib/omniauth/builder.rb:45:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.4) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.4) lib/rack/etag.rb:27:in `call'
rack (2.2.4) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.4) lib/rack/head.rb:12:in `call'
actionpack (7.0.3) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
actionpack (7.0.3) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/cookies.rb:697:in `call'
activerecord (7.0.3) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:19:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.3) lib/rails/rack/logger.rb:40:in `call_app'
railties (7.0.3) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `block in tagged'
activesupport (7.0.3) lib/active_support/tagged_logging.rb:38:in `tagged'
activesupport (7.0.3) lib/active_support/tagged_logging.rb:114:in `tagged'
railties (7.0.3) lib/rails/rack/logger.rb:25:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.4) lib/rack/method_override.rb:24:in `call'
rack (2.2.4) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/server_timing.rb:20:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.3) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
railties (7.0.3) lib/rails/engine.rb:530:in `call'
puma (5.6.4) lib/puma/configuration.rb:252:in `call'
puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
puma (5.6.4) lib/puma/server.rb:441:in `process_client'
puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

```

Settings on outseta embedded signup:
<img width="537" alt="image" src="https://github.com/tiltcamp/omniauth-outseta/assets/31795690/414694b6-1b2c-47b4-b4d2-c46c3f4dfed3">

**Comment by serhiijun** [comment]
@mattwebbio can you help me with this, please?😅

**Comment by mattwebbio** [comment]
Is this after performing a login?

**Comment by mattwebbio** [comment]
Oh, I see what you've done. You've entered the auth callback URL into the confirmation email field, which is not how this gem works

**Comment by mattwebbio** [comment]
You need to put that URL in the "sign up callback URL" field instead

**Comment by mattwebbio** [comment]
When you [create the "sign in with Outseta" button/link](https://github.com/tiltcamp/omniauth-outseta#without-database-authenticatable), it'll automatically pass the callback URL to Outseta. The URL in the confirmation email unfortunately doesn't supply a JWT for signing in the user, so what you're doing won't work
